name: Publish Android Release
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish_android_release:
    name: Generate Android Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: upload-keystore.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      - name: Create key.properties file
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Generate Google Play release notes
        run: dart distribution/android/generate_play_whatsnew.dart --version=${{ github.ref_name }}
      - run: flutter pub get
      - name: Start Android Release Build
        run: flutter build appbundle
      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-release-artifacts
          path: build/app/outputs/bundle/release/app-release.aab
      - name: Release Build to internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_PLAYSTORE_ACCOUNT_KEY }}
          packageName: es.victorcarreras.background_remover
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          whatsNewDirectory: distribution/android/whatsnew
          tracks: production
          status: completed
